### ISSUE TITLE
Trying to work in PyCharm

### ISSUE THREAD

**Issue by vidheyoza** [rebrik/OpenSimFullBodyWithPython#1]
I have successfully installed OpenSim, and arranged the directories of the repo as given in the README. When I try to run the file `simulateWalk.py` or `simulateRun.py` in PyCharm after altering the `curPath` accordingly, I get the following error: 

`runfile('/Users/vidhey/coding/Python/elimax/SimulationDataAndSetupFiles4.0/Python/simulateWalk.py', wdir='/Users/vidhey/coding/Python/elimax/SimulationDataAndSetupFiles-4.0/Python')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/vidhey/coding/Python/elimax/SimulationDataAndSetupFiles-4.0/Python/simulateWalk.py", line 30, in <module>
    rc = runProgram(cmdfull)
  File "/Users/vidhey/coding/Python/elimax/SimulationDataAndSetupFiles-4.0/Python/simFunctions.py", line 10, in runProgram
    stderr=subprocess.STDOUT)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

How do I solve this? I'm not very well versed with `subprocess` package, so I'm sure what changes to make there to run the code on PyCharm.

**Comment by rebrik** [comment]
It looks like you are doing it on Windows. The scripts were tested on
Xubuntu 16.04.5 LTS 64

You can try to edit the script to comply with the Windows version of the
subprocess calls.

Sorry, can't help you with this

**Comment by vidheyoza** [comment]
I'm working on macOS not Windows, can you help me with that?
